version: '2'
services:
    webemul-app:
        image: webemul
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://webemul-mysql:3306/webemul?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8081:8081
    webemul-mysql:
        extends:
            file: mysql.yml
            service: webemul-mysql
